import { type NextPage } from "next";
import Head from "next/head";
import Layout from "../components/Layout";
import Blogs from '../components/Blogs'

const BlogPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Startup Armenia | Blogs</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Blogs/>
      </Layout>
    </>
  );
};

export default BlogPage;
