import { type NextPage } from "next";
import Head from "next/head";
import Events from '../components/Events';
import Layout from "../components/Layout";

const EventsPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Startup Armenia | Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
       <Events/>
      </Layout>
    </>
  );
};

export default EventsPage;
