import { type NextPage } from "next";
import Head from "next/head";
import Layout from "../components/Layout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
          <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
            <h3 className="text-3xl font-extrabold tracking-tight text-white sm:text-[3rem]">
              Welcome To
            </h3>
            <h1 className="text-2xl font-extrabold tracking-tight text-white sm:text-[3rem]">
              Startup Armenian Foundations Website
            </h1>
            <div className="w-full border border-b-2 border-zinc-100" />
            <h3 className="text-xl font-extrabold tracking-tight text-white sm:text-[2rem]">
              Please be aware we are currently under construction ⚠️
            </h3>
          </div>
        </main>
      </Layout>
    </>
  );
};

export default Home;
